name: koreanlearningapp
description: A new Flutter project.
# Reuse for all
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.5.0
  webview_flutter: ^4.2.0
  package_info_plus: ^8.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.2
  device_info_plus: ^10.1.0
  shorebird_code_push: ^2.0.4
  get: ^4.6.6
  flutter_svg: ^2.2.1
  lottie: ^3.3.1
  rive: ^0.13.20
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.1.1
  shimmer_animation: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml